### ISSUE TITLE
是否有兴趣加入蚂蚁金服通信中间件

### ISSUE THREAD

**Issue by dbl-x** [kuangye098/myrocketmq#1]
看到你研究了一些RocketMQ的内容，不知是否有兴趣加入蚂蚁金服做MQ相关的研发工作。我的邮箱：marklin.hz@gmail.com

**Comment by kuangye098** [comment]
不好意思，刚上个月跳槽到新公司，看到你的公众号还不错，是否能加个朋友？

**Comment by dbl-x** [comment]
好的   我的微信：l_happytime
通过公众号也可以联系到我

2018-07-13 14:20 GMT+08:00 kuangye098 <notifications@github.com>:
